# fly.toml app configuration file generated for teachinspire-yt-ingest on 2026-08-10T16:13:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teachinspire-yt-ingest'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 4
    soft_limit = 2

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
